# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import  QtWidgets,QtCore
from PyQt5.QtWidgets import  QVBoxLayout,QMessageBox,QGridLayout, QPushButton, QHBoxLayout,QComboBox
import pyqtgraph as pg


class Ui_Form(QtWidgets.QWidget): #change the class name here
    # add init function
    def __init__(self):
        super(Ui_Form, self).__init__()
        self.setupUi(self)
        

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowTitle( "Information") # change window name here


        formbody = QVBoxLayout() #use vertical layout

        # set graph windows
        self.graph = pg.PlotWidget() 
        self.atrialgraph = pg.PlotWidget()

        # set information tab windows
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.device = QtWidgets.QWidget()
        self.device.setObjectName("device")
        self.tabWidget.addTab(self.device, "")
        self.User = QtWidgets.QWidget()
        self.User.setObjectName("User")

        self.tabWidget.addTab(self.device, "")
        self.tabWidget.addTab(self.User, "")
        self.tabWidget.setTabText(0,"Device Info")
        self.tabWidget.setTabText(1,"User Action")
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget.setFixedHeight(300)

        deviceLayout = QGridLayout()
        userLayout = QGridLayout()
        

        # device part
        
        self.connect = QtWidgets.QLabel("No Device Connected")
        #self.battery = QtWidgets.QLabel("No Bateries Information")
        deviceLayout.addWidget(self.connect,0,0)
        #deviceLayout.addWidget(self.battery,1,0)
        self.device.setLayout(deviceLayout)

        # users part
        self.username = QtWidgets.QLabel("User Name")
        self.B_Logout = QtWidgets.QPushButton("Logout")
        userLayout.addWidget(self.username,0,0)
        userLayout.addWidget(self.B_Logout,1,0)
        self.User.setLayout(userLayout)

        """
        Test button, will be removed after formal deployment
        """
        self.test = QtWidgets.QWidget()
        testLayout = QHBoxLayout()
        self.testConnect = QPushButton("Connect")
        self.testUnconnect = QPushButton("Unconnect")
        self.showEgram = QPushButton("Start Egram")
        self.stopEgram = QPushButton("Stop Egram")
        self.export = QPushButton("Export Report")
        self.port = QComboBox()
        
        testLayout.addWidget(self.port)
        testLayout.addWidget(self.testConnect)
        testLayout.addWidget(self.testUnconnect)
        testLayout.addWidget(self.showEgram)
        testLayout.addWidget(self.stopEgram)
        testLayout.addWidget(self.export)
        self.test.setLayout(testLayout)
        formbody.addWidget(self.test)
        """
        Test button end, will be removed after formal deployment
        """

        # add component to windows
        formbody.addWidget(QtWidgets.QLabel('Atrium Signals'))
        formbody.addWidget(self.atrialgraph)
        formbody.addWidget(QtWidgets.QLabel('Ventricle Signals'))
        formbody.addWidget(self.graph)
        formbody.addWidget(self.tabWidget)
        self.setLayout(formbody) #set layout
        formbody.setSpacing(20)

   
        # add sampling timmer
        self.timer = QtCore.QTimer(self)


    def confirm(self,mes):
        result= QMessageBox.question(self, 'Confirm Action', mes, QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        return result
    def showMsg(self,type,str):
        QMessageBox.about(self, type, str)






        