# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QFormLayout, QMessageBox

class Ui_Register(QtWidgets.QWidget):#change the class name here
    # add init function
    def __init__(self):
        super(Ui_Register, self).__init__()
        self.setupUi(self)

    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(560, 200)

        formbody = QFormLayout() # add form layout
        self.B_Register = QtWidgets.QPushButton(Register)
        self.B_Register.setObjectName("B_Register")
        self.I_Password = QtWidgets.QLineEdit(Register)
        self.I_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.I_Password.setObjectName("I_Password")
        self.I_UserName = QtWidgets.QLineEdit(Register)
        self.I_UserName.setObjectName("I_UserName")
        self.I_PasswordRe = QtWidgets.QLineEdit(Register)
        self.I_PasswordRe.setEchoMode(QtWidgets.QLineEdit.Password)
        self.I_PasswordRe.setObjectName("I_PasswordRe")

        # add component to form
        formbody.addRow("User Name",self.I_UserName)
        formbody.addRow("Password", self.I_Password )
        formbody.addRow("Repeat Password",self.I_PasswordRe)
        formbody.addRow(self.B_Register)
        formbody.setSpacing(20)
        self.setLayout(formbody) #set layout

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Register")) #change the name here
        self.B_Register.setText(_translate("Register", "Register New User"))
        
    def showMsg(self,str1,str2):
        QMessageBox.about(self, str1, str2)
