# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(927, 295)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(130, 50, 531, 191))
        self.tabWidget.setObjectName("tabWidget")
        self.device = QtWidgets.QWidget()
        self.device.setObjectName("device")
        self.gridLayoutWidget = QtWidgets.QWidget(self.device)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 50, 160, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget.addTab(self.device, "")
        self.User = QtWidgets.QWidget()
        self.User.setObjectName("User")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.User)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(80, 60, 160, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget.addTab(self.User, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.device), _translate("Form", "Device"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.User), _translate("Form", "User Profile"))
