# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(560, 300)
        self.B_Register = QtWidgets.QPushButton(Register)
        self.B_Register.setGeometry(QtCore.QRect(180, 220, 121, 28))
        self.B_Register.setObjectName("B_Register")
        self.I_Password = QtWidgets.QLineEdit(Register)
        self.I_Password.setGeometry(QtCore.QRect(180, 110, 271, 22))
        self.I_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.I_Password.setObjectName("I_Password")
        self.L_password = QtWidgets.QLabel(Register)
        self.L_password.setGeometry(QtCore.QRect(60, 100, 81, 31))
        self.L_password.setObjectName("L_password")
        self.L_UserName = QtWidgets.QLabel(Register)
        self.L_UserName.setGeometry(QtCore.QRect(60, 40, 81, 31))
        self.L_UserName.setObjectName("L_UserName")
        self.I_UserName = QtWidgets.QLineEdit(Register)
        self.I_UserName.setGeometry(QtCore.QRect(180, 50, 271, 22))
        self.I_UserName.setObjectName("I_UserName")
        self.L_passwordRe = QtWidgets.QLabel(Register)
        self.L_passwordRe.setGeometry(QtCore.QRect(60, 160, 111, 31))
        self.L_passwordRe.setObjectName("L_passwordRe")
        self.I_PasswordRe = QtWidgets.QLineEdit(Register)
        self.I_PasswordRe.setGeometry(QtCore.QRect(180, 170, 271, 22))
        self.I_PasswordRe.setEchoMode(QtWidgets.QLineEdit.Password)
        self.I_PasswordRe.setObjectName("I_PasswordRe")

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Form"))
        self.B_Register.setText(_translate("Register", "Register New User"))
        self.L_password.setText(_translate("Register", "PassWord"))
        self.L_UserName.setText(_translate("Register", "User Name"))
        self.L_passwordRe.setText(_translate("Register", "Repeat PassWord"))
